# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2442e5b663df33c391fc2fe4b1a3f5082721de72526b24b04a3ed4dee38119b17e5161eaaebd5ad7c840c24f31e462780c0174015dc91ca3cb97b5edcc3b7c9

test:
  secret_key_base: 8dd27dbb69a570a875646d623082532ef2886423e416a03d21fc4496fdb07be8d98f3fc7c252aba3372728cd3e4bad99895dbed15c0625acfc4c602f9e496fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
